knp_paginator:
    page_range: 5                      # Number of pages displayed in the pagination bar
    default_options:
        page_name: page                # Name of the request parameter for page number
        sort_field_name: sort          # Name of the request parameter for sorting
        sort_direction_name: direction # Name of the request parameter for sorting direction
        distinct: true                 # Ensure distinct results
