controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_client_honoraires_index:
  path: /client/{id}
  controller: App\Controller\ClientController::honorairesIndex

number_to_words:
  path: "/convert"
  controller: 'App\Controller\PdfController::convertToWords'
  methods: ["GET"]
